kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metrics-collection-role-binding
subjects:
- kind: ServiceAccount
  name: metrics-collection-sa
roleRef:
  kind: Role
  name: metrics-collection-role
  apiGroup: rbac.authorization.k8s.io
